file_format: "1"
id: catpucciano
name: CATPUCCIANO
type: shield
url: https://github.com/GEIGEIGEIST/TOTEM
requires: [seeeduino_xiao_ble]
features:
  - keys
siblings:
  - catpucciano_left
  - catpucciano_right
